- hosts: app-vm
  tasks:
    - name: Install plugins for jenkins
      uri:
        url: http://{{ ansible_host }}:8080/pluginManager/installNecessaryPlugins
        method: POST
        user: admin
        password: password
        body: |
          [
            {"shortName": "kubernetes"},
            {"shortName": "git"},
            {"shortName": "pipeline"},
            {"shortName": "docker"}
          ]
        headers:
          Content-Type: application/json
        status_code: 200, 201

    - name: create Jenkins job for CI/CD pipeline
      uri:
        url: http://{{ ansible_host }}:8080/createItem?name=CI-CD-Pipeline
        method: POST
        user: admin
        password: password
        body: "{{ lookup('file', 'pipeline-config.xml') }}"
        headers:
          Content-Type: application/xml
        status_code: 200, 201
