- hosts: app-vm
  tasks:
    - name: create Kubernetes namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: java-app

    - name: create Kubernetes deployment
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: java-app
            namespace: java-app
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: java-app
            template:
              metadata:
                labels:
                  app: java-app
              spec:
                containers:
                - name: java-app
                  image: java-app-image:latest
