<flow-definition plugin="workflow-job@2.39">
    <definition class="org.jenkinsci.plugins.workflow.cps.CpsFlowDefinition" plugin="workflow-cps@2.80">
        <script>
            pipeline {
                agent any
                stages {
                    stage('Build') {
                        steps {
                            sh 'mvn clean package'
                        }
                    }
                    stage('Test') {
                        steps {
                            sh 'mvn test'
                        }
                    }
                    stage('Deploy') {
                        steps {
                            kubernetesDeploy(
                                configs: 'kubernetes/deployment.yaml',
                                kubeconfigId: 'kubeconfig',
                                enableConfigSubstitution: true
                            )
                        }
                    }
                }
            }
        </script>
        <sandbox>true</sandbox>
    </definition>
    <triggers/>
    <disabled>false</disabled>
</flow-definition>
